---
title: "PERCEIVE POLAR"
output: html_document
---

Load libraries

```{r warning=FALSE, results='hide', echo=F}
# library(ggplot2)
# library(leaflet)
# library(dplyr)
# library(cetcolor)
# library(XML)
library(tidyr)
# library(geosphere)
# library(zoo)
# library(RColorBrewer)
library(dplyr)
library(stringr)
library(xml2)
# fix time by timezone
library(lutz)
library(lubridate)
```

Load functions

```{r}
# read tcx
source('src/readTCX.R')
# supporting functions
source('src/supporting.R')
# get list of files for each participatn
source('src/getFilesZipByID.R')
# get activity information
source('src/getActivityInfo.R')
# process activity
source('src/processActivity.R')
# summarise results
source('src/summariseResults.R')
```

# MAIN RUN

Run the whole process

read the participants ids and maxhr from csv and run the process for each file

```{r}
# maxhr <- 200
# id <- 'TST_001'
#### define zipfile with activities
# zipfile <- 'input/participants.zip'
# zipfile <- 'input/PERCEIVE_240718.zip'
# zipfile <- 'input/PERCEIVE_240722.zip'
zipfile <- 'input/PERCEIVE_240723.zip'


#### read ids and maxhr
# input <- read.csv("input.csv", header=T, stringsAsFactors = F)
input <- read.csv("input/polar_id_maxhr_240718.csv", header=T, stringsAsFactors = F)
input
```


```{r}
perceive_all <- NULL
# get start time
start_time <- Sys.time()
# for (i in 1:nrow(input[1:2,])) {
for (i in 1:nrow(input)) {
  # read id and maxhr
  id <- input$id[i]
  maxhr <- input$maxhr[i]
  writeLines(c("","###############################",
               "Calculating data...",
               paste0("Working with id: ", id, " (", i, "/", dim(input)[1], ")  |  ", format(Sys.time(), "%H:%M")), ""))
  # read files
  files <- get_files_id(id = id, zipfile = zipfile)
  for (file in files) {
    # for (file in files[1]) {
    # skip if file is NA
    if(is.na(file)) {next}
    # get time from start_time in minutes
    elapsed <- as.numeric(round(difftime(Sys.time(), start_time, units = "min"), 1))
    if(which (files == file) == 1 | which (files == file) %% 20 == 0) {
      # read zip file
      writeLines(paste0("##  ", elapsed, " min\t| (", which (files == file), "/", length(files), ") Working with file: ", file))
    }
    polar_act <- process_polarfile(filename = file, zipfile = zipfile, id = id, maxhr = maxhr)
    perceive_all <- plyr::rbind.fill(perceive_all, polar_act)
  }
  # save(perceive_all,file='out/perceive_all.rda')
}
```


```{r}
# filename <- get_list_files('BG-2311', zipfile)[4]
# filename <- 'PERCEIVE_240718/BG-2311/PERCEIVE_2311_2023-07-24_09-33-46.TCX'
# filename <- 'PERCEIVE_240718/NK-2729/perceive_rct_2023-07-20_17-00-00.TCX'
# i <- 7
# id <- input$id[i]
# maxhr <- input$maxhr[i]
# polar_file <- unz(zipfile, filename)
# polar <- readTCX(polar_file)
```

```{r}
perceive_all
```


## Step 3

### SUMMARIZE STUFF

split training.all into correct sessions, duplicate and error


```{r}
# get results
results <- sum_results(perceive_all)
perceive_info <- results$perceive_info
all.activities <- results$all.activities
error.sessions <- results$error.sessions
perceive_info
```



```{r}
# save results
save(perceive_info, perceive_all, all.activities, error.sessions, file=
       paste0("out/perceive_results_",format(as.Date(Sys.Date()),format="%y%m%d"),".rda"))
```

```{r}
# save all in an XLSX file
sheet_list <- list("participants" = perceive_info,
                   "activities" = all.activities,
                   "errors" = error.sessions
                   )
openxlsx::write.xlsx(sheet_list, keepNA = FALSE,
           file=paste0("out/perceive_results_", format(as.Date(Sys.Date()), format = "%y%m%d"),".xlsx"))
```


